const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const config = require('./config');

const generateSwaggerDocs = (app) => 
{
    const options = {
        definition: {
        openapi: '3.0.1',
        info: {
            title: 'Nodejs - Express - MongoDB Rest Api Example',
            version: '1.0.0',
            description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
        },
        components: {
            securitySchemes: {
                bearerAuth: {
                    type: "http",
                    scheme: "bearer",
                    bearerFormat: "JWT",
                }
            }
        },
        // security: [
        //     {
        //         bearerAuth: []
        //     }
        // ],
        servers: [
                {
                    url: config.apiUrl,
                },
            ],

        },
        apis: ['./docs/*.js'],
    };

    app.use(config.docsEndpoint, swaggerUi.serve, swaggerUi.setup(swaggerJsdoc(options)));
  }

  module.exports.generateSwaggerDocs = generateSwaggerDocs;